# Generated by Django 5.2.7 on 2025-10-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentary',
            field=models.ManyToManyField(related_name='posts', to='post.commentary', verbose_name='Комментарии'),
        ),
    ]
