# Generated by Django 5.2.7 on 2025-11-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentary',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='post.commentary', verbose_name='Комментарии'),
        ),
    ]
