# Generated by Django 5.2.7 on 2025-11-30 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentary',
        ),
        migrations.AddField(
            model_name='post',
            name='commentary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='post.commentary', verbose_name='Комментарии'),
        ),
    ]
