# Generated by Django 5.2.7 on 2025-11-30 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_alter_commentary_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="commentary",
        ),
        migrations.AddField(
            model_name="commentary",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentaries",
                to="post.post",
                verbose_name="Пост",
            ),
        ),
    ]
